# Generated by Django 2.0.2 on 2018-02-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reconds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('inputfile_name', models.CharField(max_length=200)),
                ('inputfile', models.FileField(upload_to='./sequence_file')),
                ('outputfile', models.FileField(upload_to='./sequence_file')),
                ('submit_data', models.DateTimeField()),
            ],
        ),
    ]
