# Generated by Django 2.0.2 on 2018-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('inputfile', models.FileField(upload_to='species_tree/recordsfile/')),
                ('outputfile', models.FileField(upload_to='species_tree/recordsfile/')),
                ('submit_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
