# Generated by Django 2.0.2 on 2018-02-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('inputfile', models.FileField(upload_to='./sequence_file')),
                ('outputfile', models.FileField(upload_to='./sequence_file')),
                ('submit_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Reconds',
        ),
    ]
